services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: splitthebill
      POSTGRES_USER: splitthebill
      POSTGRES_PASSWORD: splitthebill
    ports:
      - "5432:5432"
    volumes:
      - splitthebill_pg_data:/var/lib/postgresql/data

volumes:
  splitthebill_pg_data:
